service: palm-risk-poc

provider:
  name: aws
  runtime: python3.7
  timeout: 30
  profile: default
  memorySize: 3008
  region: 'us-east-1'
  role: arn:aws:iam::838255262149:role/gfw_lambda_tiles
  deploymentBucket: gfw2-data
  iamRoleStatements:
    - Effect: "Allow"
      Action:
         - "s3:*"
      Resource:
         - 'arn:aws:s3:::gfw2-data'

package:
  artifact: dist/raster-ops-deploy.zip

functions:
  glad-alerts:
    handler: wsgi.handler
    events:
      - http: ANY /
      - http: ANY {proxy+}

